### ISSUE TITLE
ImportError: no module named 'adafruit_hid.gamepad'

### ISSUE THREAD

**Issue by chaosjockey** [ArlanPrado/RPico-Clone-Hero-Controller#4]
Been racking my brain to find the gamepad.mpy library but I haven't been able to find it anywhere. After going back through all of circuitpython releases even the 6.x libraries don't contain gamepad.mpy.

Would you be able to provide said library here on yourr github or is there something I'm overlooking?

**Comment by ArlanPrado** [comment]
Yeah you're right, I can't find gamepad.mpy in their 6.x and 8.x libraries. I added the gamepad.mpy into my repo just now. Hopefully it works for you.
